# Generated by Django 5.0.1 on 2024-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuesaapp', '0003_financial_secretary_general_secretary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welfare_Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='candidate_pics/')),
                ('department', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
    ]
