# Generated by Django 5.0.1 on 2024-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuesaapp', '0006_assistant_general_secretary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant_general_secretary',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistant_social_director',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financial_secretary',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general_secretary',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_r_o1',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_r_o2',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='president',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='public_relations_officer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='social_director',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sports_director',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technical_director',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treasurer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vice_president',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='welfare_director',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
