# Generated by Django 5.0.1 on 2024-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuesaapp', '0012_votestatus_matric_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matric_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
