# Generated by Django 5.0.1 on 2024-02-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuesaapp', '0013_remove_userprofile_user_userprofile_has_voted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteStatus',
        ),
    ]
